name: goipvc
description: A different frontend for the myipvc app
publish_to: 'none'

version: 0.19.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.6
  dio: ^5.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  crypto: ^3.0.3
  tuple: ^2.0.2
  encrypt: ^5.0.1
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.7
  syncfusion_flutter_calendar: ^23.1.36
  syncfusion_localizations: ^23.1.36
  url_launcher: ^6.1.14
  photo_view: ^0.14.0
  package_info_plus: ^4.1.0
  flutter_cache_manager: ^3.3.1
  open_file_plus: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.0.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/ipvc.png
     - assets/ipvc-divider.svg
     - assets/ipvc-logo.svg
     - assets/ESA-logo.svg
     - assets/ESCE-logo.svg
     - assets/ESDL-logo.svg
     - assets/ESE-logo.svg
     - assets/ESS-logo.svg
     - assets/ESTG-logo.svg
     - assets/logo.png

     - assets/floors/estg/dark1.png
     - assets/floors/estg/dark2.png
     - assets/floors/estg/dark3.png
     - assets/floors/estg/light1.png
     - assets/floors/estg/light2.png
     - assets/floors/estg/light3.png

     - assets/calendar.png