# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: Build Flutter (Android + iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: /pubspec.yaml
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.read-version.outputs.version-number }}
          token: ${{ secrets.GH_TOKEN }}